monolog:
    handlers:
        main:
            type: stream
            path: "php://stderr"
            level: debug # info, notice, warning or error but I keep it at debug to start out
            formatter: app.monolog.formatter.cloudwatch

services:
    # default format but without date ~ cloudwatch adds that automatically
    app.monolog.formatter.cloudwatch:
        class: Monolog\Formatter\LineFormatter
        arguments: ["%%channel%%.%%level_name%%: %%message%% %%context%% %%extra%%\n"]